#
# Find CONFIG include directories and libraries
#
# CONFIG_INCLUDE_DIR
# CONFIG_LIBRARY_DIR
# CONFIG_LIBRARY
# CONFIG_FOUND

FOREACH(ROOT ${COTS_PATHS} ${LIB_IO_ROOT})

  FIND_PATH(CONFIG_INCLUDE_DIR configuration.hh
    ${ROOT}/include
    )
  
  FIND_LIBRARY(CONFIG_LIBRARY configuration
    ${CONFIG_INCLUDE_DIR}/../lib/
    )
  
  IF(CONFIG_INCLUDE_DIR)
    IF(CONFIG_LIBRARY)
      SET(CONFIG_FOUND "YES")
      GET_FILENAME_COMPONENT(CONFIG_LIBRARY_DIR ${CONFIG_LIBRARY} PATH)
      BREAK()
    ENDIF(CONFIG_LIBRARY)
  ENDIF(CONFIG_INCLUDE_DIR)
    
ENDFOREACH(ROOT)
