#
# Find NCMAP include directories and libraries
#
# NCMAP_INCLUDE_DIR
# NCMAP_LIBRARY_DIR
# NCMAP_LIBRARY
# NCMAP_FOUND

FOREACH(ROOT ${COTS_PATHS} ${LIB_IO_ROOT})

  FIND_PATH(NCMAP_INCLUDE_DIR ncmap.hh
    ${ROOT}/include
    ${ROOT}/ncmap/src
    )

  FIND_LIBRARY(NCMAP_LIBRARY ncmap
    ${NCMAP_INCLUDE_DIR}/../lib/
    )

  IF(NCMAP_INCLUDE_DIR)
    IF(NCMAP_LIBRARY)
      SET(NCMAP_FOUND "YES")
      GET_FILENAME_COMPONENT(NCMAP_LIBRARY_DIR ${NCMAP_LIBRARY} PATH)
      BREAK()
    ENDIF(NCMAP_LIBRARY)
  ENDIF(NCMAP_INCLUDE_DIR)
    
ENDFOREACH(ROOT)
