#
# Find NETCDF include directories and libraries
#
# NETCDF_INCLUDE_DIR
# NETCDF_LIBRARY_DIR
# NETCDF_LIBRARY
# NETCDF_FOUND

FOREACH(ROOT ${COTS_PATHS})

  FIND_PATH(NETCDF_INCLUDE_DIR netcdf
    ${ROOT}/include
    NO_DEFAULT_PATH
    )
  
  FIND_LIBRARY(NETCDF_LIBRARY netcdf netcdf_c++4
    ${NETCDF_INCLUDE_DIR}/../lib
    NO_DEFAULT_PATH
    )
  
  IF(NETCDF_INCLUDE_DIR)
    IF(NETCDF_LIBRARY)
	  SET(NETCDF_FOUND "YES")
	  GET_FILENAME_COMPONENT(NETCDF_LIBRARY_DIR ${NETCDF_LIBRARY} PATH)
    ENDIF(NETCDF_LIBRARY)
  ENDIF(NETCDF_INCLUDE_DIR)
  
ENDFOREACH(ROOT)
