#
# Find XML2 include directories and libraries
#
# XML2_INCLUDE_DIR
# XML2_LIBRARY_DIR
# XML2_LIBRARY
# XML2_FOUND

FOREACH(ROOT ${COTS_PATHS})

  FIND_PATH(XML2_INCLUDE_DIR libxml
    ${ROOT}/include
    )
  
  FIND_LIBRARY(XML2_LIBRARY xml2
    ${XML2_INCLUDE_DIR}/../lib
    NO_DEFAULT_PATH
    )
  
  IF(XML2_INCLUDE_DIR)
    IF(XML2_LIBRARY)
	  SET(XML2_FOUND "YES")
	  GET_FILENAME_COMPONENT(XML2_LIBRARY_DIR ${XML2_LIBRARY} PATH)
    ENDIF(XML2_LIBRARY)
  ENDIF(XML2_INCLUDE_DIR)
  
ENDFOREACH(ROOT)
