import numpy as np
import matplotlib.pyplot as plt
from common.io.writeToa import readToa
from common.io.readMat import readMat

#  This script is to test the output generated by GM and compared with the outputs of the teacher
indir = '/home/renefiedel/Documents/EO DATA PROCESSING/EODP/EODP/eodp_gm-master/bin/output_dir'
mytoa = readToa(indir, "geolocation.nc")

refoutdir = '/home/renefiedel/Documents/EO DATA PROCESSING/EODP_TER-20200917T082333Z-001/EODP_TER/EODP-TS-E2E/gm_out'
reftoa = readToa(refoutdir, "geolocation.nc")

difftoa = np.max(np.abs(mytoa - reftoa) / reftoa)
print(difftoa * 100)
plt.plot(difftoa)
